### PR TITLE
update com.tencent.puerts.core.yml

### PR DESCRIPTION
**Pull request by zombieyang**
change the repo's url

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @zombieyang,

Thanks for the contribution.

Since puerts doesn't have a UPM version, your version is considered as a community bundle.

For the community bundle, I suggest you
- submit a new package entry and change the package name to something like `com.community.puerts` or simple `com.yourname.contrib.puerts` to avoid confusion with potential puerts [upm releases in the future](https://github.com/Tencent/puerts/issues/83).
- create at least one versioned Git tag, e.g. `0.0.1-pre`.
- optionally, change the GitHub repo name to something like puerts-upm or puerts-unity.

I will close this one, and look forward to your new package submission.

**Comment by favoyang** [comment]
BTW, if you want to strictly follow tencent purerts releases. Please fork https://github.com/Tencent/puerts and just create versioned Git tag `1.2.4-pre` from it's [upm branch](https://github.com/Tencent/puerts/tree/upm). Then resubmit your PR with the forked repository.

**Comment by favoyang** [comment]
I also noticed that https://github.com/Tencent/puerts/blob/upm/package.json's license field (MIT) is misleading. The project is licensed under the BSD 3-Clause license.

**Comment by zombieyang** [comment]
Thanks for your suggestion.

I plan to support OpenUPM on puerts v1.3, which will be released on maybe April 1st. I will submit a new PR after that release.

**Pull request closed without merging**
