### PR TITLE
Update Google packages.

### PR DESCRIPTION
**Pull request by pauvallespi**

### CODE REVIEW

**Comment by favoyang** [comment]
@pauvallespi 
Why all the repoUrl fields you changed doesn't exist? i.e. https://github.com/google/play-core-unity

**Comment by pauvallespi** [comment]
> @pauvallespi Why all the repoUrl fields you changed doesn't exist? i.e. https://github.com/google/play-core-unity

Hey @favoyang, we're still figuring out the last details for our documentation, so I set the PR as draft in the meantime. I will ping you when it's ready for review!

**Comment by favoyang** [comment]
Good to know, please go ahead.

**Comment by pauvallespi** [comment]
> Good to know, please go ahead.

Hey @favoyang, just letting you know that we're ready now to submit this!

**Comment by pauvallespi** [comment]
> If you find a specific package didn't catch up, please let me know the package name.

Thanks!

Looks like `com.google.play.integrity`, `com.google.play.assetdelivery`, `com.google.play.appupdate`, `com.google.play.core` and `com.google.play.common` haven't catched up yet.

**Comment by favoyang** [comment]
com.google.play.integrity https://github.com/google/play-integrity-unity
- package.json version 1.4.0: https://github.com/google/play-integrity-unity/blob/main/com.google.play.integrity/package.json
- Git tag 1.4.0, package.json version 1.3.1 https://github.com/google/play-integrity-unity/commit/2df54f7335656eaa405bcbd5a8243d17039570dc#diff-f29e1d118c0bdee07e78dd409c8d969c42a0a544a0b404e83401e0c1f81d921f

The Git tag 1.4.0 was created before the package.json version bump. Our pipeline published 1.3.1 as a result. (It's a known issue in our pipeline it accepts a Git tag that doesn't match with the actual package.json version).

To fix this, you must bump to 1.4.1 and create a new Git tag.

**Comment by favoyang** [comment]
It is possible, but you need my assistant to manually reset the pipelines for that specific version. Because the pipeline ignores an already published Git tag.

**Comment by favoyang** [comment]
com.google.play.appupdate
- Git tag version 1.8.3
- package version 1.8.1
- pipeline: rejected https://openupm.com/packages/com.google.play.appupdate/?subPage=pipelines

To fix it, recreate Git tag 1.8.3. Our pipeline will catch up. (Our pipeline detects the Git tag change for a failed Git tag build and rebuilds it automatically.)

**Comment by favoyang** [comment]
> @favoyang If that's okay, we'd rather do that. Let me know if I can remove the tag and re-release

Okay, leave a message when you recreated the Git tag 1.4.0 for com.google.play.integrity https://github.com/google/play-integrity-unity

**Comment by pauvallespi** [comment]
> > @favoyang If that's okay, we'd rather do that. Let me know if I can remove the tag and re-release
> 
> Okay, leave a message when you recreated the Git tag 1.4.0 for com.google.play.integrity https://github.com/google/play-integrity-unity

Just recreated the tag for:
- com.google.play.integrity
- com.google.play.appupdate
- com.google.play.assetdelivery
- com.google.play.core
- com.google.play.common

Let me know if there's anything else needed from my side!

**Comment by favoyang** [comment]
- com.google.play.integrity published 1.4.0 
- com.google.play.appupdate (It works before, latest version/Git tag 1.8.3)
- com.google.play.assetdelivery published 1.9.2
- com.google.play.core published 1.8.5
- com.google.play.common published 1.9.2

It should all synced.

**Comment by pauvallespi** [comment]
Thank you very much!

**Pull request merged**
