### PR TITLE
FuXi-v1.0.10

### PR DESCRIPTION
**Pull request by mistletoeKANO**
1. 修复 资源 引用分析 窗口 运行时 Editor 模式 BUG
2. 修复 样式 加载出错BUG

### CODE REVIEW

**Comment by favoyang** [comment]
@mistletoeKANO 

If you keep sending no-sense PR like this (merge commits into dependabot/npm_and_yarn/eventsource-1.1.1 from master), you will be blocked from this project.

**Comment by mistletoeKANO** [comment]
I'm sorry, i dont know i cant do this, i dont konw how to pull my project to upm

**Comment by mistletoeKANO** [comment]
or i neednt do anthing about my change?

**Comment by favoyang** [comment]
@mistletoeKANO to submit a new package, please use the submit button on the website.

BTW, you don't need to notify OpenUPM when releasing a new version, it will be handled automatically.

**Comment by mistletoeKANO** [comment]
ok, thank you for your information.

**Pull request closed without merging**
