### PR TITLE
chore(data): new package org.pcsoft.build-tooling

### PR DESCRIPTION
**Pull request by KleinerHacker**

### CODE REVIEW

**Comment by KleinerHacker** [comment]
Please let me know how to add required dependency to com.marijnzwemmer.unity-toolbar-extender:1.4.1

**Comment by favoyang** [comment]
> Please let me know how to add required dependency to com.marijnzwemmer.unity-toolbar-extender:1.4.1

Please update your package.json, add `com.marijnzwemmer.unity-toolbar-extender:1.4.1` to the `dependencies` field follow this article https://docs.unity3d.com/Manual/upm-dependencies.html . Then bump the version and create a new Git tag.

**Comment by KleinerHacker** [comment]
@favoyang: Thanks for reply.
I add the dependency but I get always this error:
[Package Manager Window] Cannot perform upm operation: Unable to add package [org.pcsoft.build-tooling@1.1.3]:
  Package org.pcsoft.build-tooling@1.1.3 has invalid dependencies or related test packages:
    com.marijnzwemmer.unity-toolbar-extender (dependency): Package [com.marijnzwemmer.unity-toolbar-extender@1.4.1] cannot be found [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

The package I use as dependency is stored in OpenUPN. Can you help me what is wrong?
https://github.com/KleinerHacker/unity-build-tooling/blob/master/package.json

Thank you! 👍

**Comment by favoyang** [comment]
@KleinerHacker 

Try re-run the `openupm add org.pcsoft.build-tooling` command, which will add the new dependency to the scoped list of `Packages/manifest.json`.

```
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.marijnzwemmer.unity-toolbar-extender",
        "com.openupm",
        "org.pcsoft.build-tooling"
      ]
    }
```

**Comment by KleinerHacker** [comment]
@favoyang 

Thanks. There is no way to add this information directly into the project I want to use?

Thanks.

**Comment by KleinerHacker** [comment]
@favoyang 

Year, thanks, now I understood my problem.

**Comment by favoyang** [comment]
@KleinerHacker

Well, it's a limitation of Unity Pacman that it WILL NOT search for unknown dependencies from an existing registry and add to the scoped list for users. Pacman just complains about missing a dependency.

When Unity designs Pacman, they make an assumption that this feature is limited to client's internal use cases that the scope (`com.mycompany`) is a single entry or a few known entries ahead of the time to install a new package.

As a result, when a package adds a new dependency in an update. Unity will fail to find it and you have to re-run  `openupm add` or add the missing dependency manually.

It's not user friendly, and because Unity prevents in-editor helper scripts to assist the Pacman, it became a flaw that we can not help to fix.

Behind this is perhaps a different vision of Package manager. Unity seems to treat it as a tool to manage official components, and also help clients manage their private components. Well, OpenUPM treats it as a way for sharing public components.

**Pull request merged**
