### PR TITLE
Update com.dav-sea.easy-tab.yml

### PR DESCRIPTION
**Pull request by dav-sea**

### CODE REVIEW

**Comment by favoyang** [comment]
The ~ character does not require quotes in YAML.

Is there any issue with parsing the README file without the quote?

**Comment by favoyang** [comment]
Oh, the `:` requires a quote. That makes sense.

**Comment by dav-sea** [comment]
I'm trying to figure out why the [package page](https://openupm.com/packages/com.dav-sea.easy-tab/?subPage=readme) doesn't display README.md. All I see is "See more in the [dav-sea/EasyTab](https://github.com/dav-sea/EasyTab) repository" It seems that the quotation marks did not help.

Maybe there are some ideas?

**Comment by favoyang** [comment]
I see, it should be `Docs~`, not `~Docs`.

**Pull request merged**
