### PR TITLE
chore(data): new package extensions.unity.shapes.recttransform

### PR DESCRIPTION
**Pull request by IvanMurzak**
This pull request adds a new package configuration for the Shapes RectTransform Unity extension. The configuration includes essential metadata such as the package name, description, repository URL, license, topics, and other relevant details to support package management and discovery.

- Addition of a new package metadata file `extensions.unity.shapes.recttransform.yml` with information including name, description, repository URL, license, topics, and localization fields.

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @IvanMurzak,

I found a few of your recently submitted packages have some build issues.

i.e. `extensions.unity.shapes.recttransform` https://openupm.com/packages/extensions.unity.shapes.recttransform/?subPage=pipelines

All these submitted packages are pointed to https://github.com/IvanMurzak/Unity-Extensions.

For monorepo, to keep the Git tag aligned with all these packages, there're two different strategies.
- Keep all packages version the same. That means an update for package-a@1.0.0 will trigger a version update of all packages to version 1.0.1. Then you can create a new Git tag 1.0.1.
- Create different tag prefixes for different packages. i.e. `package-a/1.0.0`, `package-b/2.0.1`. Then setup the OpenUPM's gitTagPrefix field to track the specific prefix.

You may try [ubump](https://github.com/reeseschultz/ubump) from reeseschultz ([demo project](https://github.com/reeseschultz/ReeseUnityDemos/tags)), it's a CLI tool that implements the second version management strategy.

**Comment by IvanMurzak** [comment]
Hi @favoyang,

Thanks for the suggestion. I want to split that mono-repo to dedicated. 

I hope you will add CLI command to push a package to OpenUPM directly as NPM does. Because I still hadn't figured out clearly how to set up GitHub Actions to deploy to OpenUPM. Need to spend some time reading your guides in more detail, but I don't have time for that yet.

**Comment by IvanMurzak** [comment]
@favoyang **Need your feedback, please read my message below.**

I had collided into a huge problem related to NuGet packages while integrated EntityFrameworkCore into Unity project. Seen different NuGet wrappers and solutions on GitHub for NuGet+Unity, even that one which you promoted at OpenUPM site. All of them can't handle dependencies for EntityFrameworkCore.3.1.25 without compilation errors. I did that manually using `nuget.exe` app and single command in CLI. After that need manually to delete not needed DLLs from other frameworks (such as net461, mono etc), because NuGet package contains DLLs for all supported frameworks, that can't work with Unity. 

After all of that, I just realized how great would be to have each package from NuGet as OpenUPM package. For example, imagine that: `EntityFrameworkCore.NET.Standard.2.0` as package at OpenUPM has a list of dependencies to a list of separate packages. All of them are hosted on OpenUPM, and each of them has multiple versions for different frameworks (.net461, .NET Standard 2.0, NET Standard 2.1)

image

Looks like I can create NuGet Parser, which can create multiple dedicated packages for each NuGet package from Microsoft at least. But even though it would be hundreds or maybe even a few thousands of packages. I am not sure about that idea.

**Comment by favoyang** [comment]
Hi @IvanMurzak,

Could you repost the issue on https://github.com/xoofx/UnityNuGet to get their feedback on the "NuGet package contains DLLs for all supported frameworks that don't work with Unity"?

Handling variety using the package name smells like a temporary workaround. It didn't benefit from version control which is the key part to use a package management system.

**Comment by IvanMurzak** [comment]
@favoyang the major future issue of the project https://github.com/xoofx/UnityNuGet is `.NET Standard 2.0`, which is not relevant already in .NET stack. People still use it in Unity because Unity didn't support it before Unity 2021. There is no sense to continue to use `.NET Standard 2.0` today, if only you don't have an old project at old Unity version (like me). That is why I am sure it should be multiple dedicated packages, with `.NET Standard 2.0`, `.NET Standard 2.1` and `.NET 6.0` for Unity 2022-2023. 

As Unity guys said, they are going to migrate Unity to `.NET 6.0` because it is LTS. Microsoft uses `.NET 6.0` in full power, also Microsoft had removed `.NET Standard 2.0 / 2.1` support from top packages such as EntityFrameworkCore. Technologies move forward, I don't see any reason to use .NET Standard 2.0 and be blocked by it. Just an example with EntityFrameworkCore, just version 3.X.X supports .NET Standard 2.0, EF Core 6.0.0 supports only `.NET 6.0`, EF Core 7.0.0 already in Preview, and also supports only `.NET 6.0`.

UnityNuGet will die in few years for that reason. The only way to resolve it what I see in context of UnityNuGet, is to create a separate Azure hosting for hosting the same packages but for .NET Standard 2.1, and one more dedicated hosting for .NET 6.0.

- Unity 2019: `.NET Standard 2.0`
- Unity 2020: `.NET Standard 2.0`
- Unity 2021: `.NET Standard 2.1`
- Unity 202(2 or 3): `.NET 6.0`

Hey @xoofx, could you please take a look at this topic as well? 

I don't have a goal to the critic that all, it is a great job, I just looking for scalability and solution for the future. Pretty close future.

**Comment by IvanMurzak** [comment]
* The parser should be executed only for these goals:
- parse packages from NuGet
- create graph of depdencies
- upload to OpenUPM

**Comment by xoofx** [comment]
> Hm... I just think about it from a different point of view. Does the UnityNuGet disables/enables DLLs into a single package at import time @xoofx ? Because you said, `.NET Standard 2.0` + `2.1` are supported. How exactly if not that way.
> If so, it would be even better than having tons of versions of the same package.

Yep, that's my point. At import time, we are able to say which DLL can go into the project or not and we do that for .NETStandard 2.0/2.1. In UnityNuGet, we define the constraints [here](https://github.com/xoofx/UnityNuGet/blob/c3eb9e1d3484ffc43f0ed7dee6e96a563344768a/src/UnityNuGet.Server/appsettings.json#L9-L18) and they are injected [here](https://github.com/xoofx/UnityNuGet/blob/962caffbfc910bcc8c507803bcc7ddff2ab980f8/src/UnityNuGet/RegistryCache.cs#L534-L535) via the associated meta file [here](https://github.com/xoofx/UnityNuGet/blob/962caffbfc910bcc8c507803bcc7ddff2ab980f8/src/UnityNuGet/UnityMeta.cs#L39)

So creating different packages because of different framework is really not a good idea. Unity packages do support some way of handling that with define constraints.

**Comment by favoyang** [comment]
@IvanMurzak, does @xoofx's comment make sense for you? Have you found a problem with the dynamic loading features based on constraints from UnityNuGet?

If this is the solution you're looking for, please close #3062, #3066, and #3067.

**Comment by favoyang** [comment]
> I hope you will add CLI command to push a package to OpenUPM directly as NPM does. Because I still hadn't figured out clearly how to set up GitHub Actions to deploy to OpenUPM. Need to spend some time reading your guides in more detail, but I don't have time for that yet.

Sorry, I miss this message.

It's not my current focus. Though it can be a long-term goal to migrate to a mixed registry - where some packages are delegated to the build pipelines and others are in a traditional manual publish mode. It requires more resources to invest in the service for scale.

**Comment by IvanMurzak** [comment]
> @IvanMurzak, does @xoofx's comment make sense for you? Have you found a problem with the dynamic loading features based on constraints from UnityNuGet?
> 
> If this is the solution you're looking for, please close #3062, #3066, and #3067.

Got it, I am in the middle of the investigation.  Ok, will do. I need more time.

**Pull request merged**
