### PR TITLE
Update com.newtonsoft.json.yml

### PR DESCRIPTION
**Pull request by iDreamsOfGame**

### CODE REVIEW

**Comment by favoyang** [comment]
@iDreamsOfGame please create one PR per package (a separate branch for 6b85017). The bot then will merge new package automatically.

**Comment by favoyang** [comment]
@iDreamsOfGame Shall we hold this to see whether https://github.com/PixelWizards/com.newtonsoft.json/pull/3 get merged first? or you strongly preferred to maintain this package yourself (so I will switch to use your fork).

Here's also some [history ](https://github.com/starikcetin/awesome-upm/issues/29#issuecomment-576007249)about this package if you're willing to maintain it.

In a short. Here's 3 instances
- https://github.com/jilleJr/Newtonsoft.Json-for-Unity (name: jillejr.newtonsoft.json-for-unity), the most active instance using Json.NET 12.0.3 R1 at the time of writing. This instance will be supported when its UPM branch is ready. (refs https://github.com/jilleJr/Newtonsoft.Json-for-Unity/issues/33)
- com.unity.nuget.newtonsoft-json, which is an internal package from Unity that based on 12.0.1.22727, and the 2.0.0-preview is taken from one of jilleJr's release.
- https://github.com/PixelWizards/com.newtonsoft.json (name: com.newtonsoft.json), copied from  com.unity.nuget.newtonsoft-json, with a few changes.

**Comment by iDreamsOfGame** [comment]
I think the newtonsoft.json repo of PixelWizards is no longer maintained. Since I saw you submit a pull request, and I also sumbit a pull reuquest too. Both of them have no reply or merging action. So I can maintain this repo and update the version of assembly Newtonsoft.Json.

**Comment by iDreamsOfGame** [comment]
Think for a moment, I think this pull request can be closed. I will fork jilleJr's repo and create a upm branch for OpenUPM later.

**Comment by favoyang** [comment]
Closed as requested from PR owner.

**Pull request closed without merging**
