### PR TITLE
chore(data): new package com.stansassets.facebook

### PR DESCRIPTION
**Pull request by stan-osipov**

### CODE REVIEW

**Comment by favoyang** [comment]
@stan-osipov Thanks for submitting the package, you shall put the file under `data/packages/`, not the root path.

**Comment by favoyang** [comment]
You can do that directly via the GitHub website, on your fork: https://github.com/stan-osipov/openupm

How-to: https://github.blog/2013-03-15-moving-and-renaming-files-on-github/

**Review by favoyang — CHANGES_REQUESTED** [review]
Reject reason: please move file to data/packages/ folder/.

**Comment by stan-osipov** [comment]
Thx @favoyang my bad. Fixed :)

**Comment by favoyang** [comment]
BTW, based on the [dependencies check]( https://openupm.com/packages/com.stansassets.facebook/?subPage=deps), you may want submit `com.stansassets.plugins-dev-kit` package to the platform.

**Pull request merged**
