### PR TITLE
chore(data): new package com.google.firebase.app

### PR DESCRIPTION
**Pull request by xinatcg**

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @xinatcg,

Thanks for submitting a group of `com.google.firebase` packages.

Before I dig into these packages, please review this thread: https://github.com/firebase/quickstart-unity/issues/1030.

If your submissions are compatible with [Unity Package Guidelines](https://unity3d.com/legal/terms-of-service/software/package-guidelines), especially answered my concern on this comment https://github.com/firebase/quickstart-unity/issues/1030#issuecomment-826249998. I will merge them.

**Comment by xinatcg** [comment]
Yes, i have checked this thread.
The reason to publish is that Google shut down the registry. 

all these firebase packages is download the tgz from this link.

https://developers.google.com/unity/archive#google_analytics_for_firebase

I write some automation script which can automatically maintain all these firebase repo in my GitHub
such as firebase just released a new version 9.0.0, I use my script auto-update all my git repo with the update.

**Comment by xinatcg** [comment]
actually, i also create the com.google.android and com.google.play. But there are existing package already in the openupm. The base one is the latest version and from the official repo. so I think it is fine. but some of package from non-official, I am afraid will not be updated in future. but there package is not necessary for us by openupm, we can use git. 

we use openupm because we want to create our base unity shared lib, Based on my test the package.json dependency cannot use the GitHub link.

**Comment by xinatcg** [comment]
sorry, just read the term thing. then maybe that still be the issue ...

**Comment by favoyang** [comment]
Then you must notice that they shut down the registry because the packages can not comply with Unity's terms. And Google guys just give up. My comment above explains the detail.

If what you've done is upload tgz files to your own repository and create versioned Git tags. You're accessible to do it since Unity terms do not apply to the Git repository.

But all terms are applying to a public registry. If you do not answer the concern for my comment above. I can not take the risk to publish them.

We do have some legacy packages for com.google scope. I don't know if they're fully comply with the terms. I mean I have to remove them if Unity complains about it. (But no one complain so far.).

**Comment by favoyang** [comment]
Well, you can set up your private registry and publish them for your internal usage. This is the only way I know that is safe to use these packages.

Obviously, Google is not a bad guy for creating these packages. I don't think Google is leveraging these packages to create a storefront or so. I personally think the terms are hurting the ecosystem. But it's not something I can decide. It's up to Unity to decide what is best for their product and their stakeholders.

**Comment by favoyang** [comment]
I will close your firebase submission for terms reasons. I hope in the future Unity can revisit its policy to bring them back. Sorry for the frustrating experience.

**Comment by favoyang** [comment]
I suggest you submit to https://github.com/starikcetin/awesome-upm, which has a more loosely policy for GitHub hosted packages.

**Comment by xinatcg** [comment]
> I suggest you submit to https://github.com/starikcetin/awesome-upm, which has a more loosely policy for GitHub hosted packages.

thanks, np. i will check it.

**Comment by xinatcg** [comment]
@favoyang  may i ask a technical question for UPM. i try to add some DLL into the UPM package. but I find when I use the UPM in a project, the DLL class is totally empty. But these DLLs work if imported to the project directly. Is there any special for DLL in UPM?

**Comment by favoyang** [comment]
Could you provide an example package and some test code to look into?

Perhaps something to do with the import settings or Assembly Info Targets?

image

https://discord.gg/FnUgWEP community may help you more.

**Pull request closed without merging**
