### PR TITLE
chore(data): new package games.feed.destringer

### PR DESCRIPTION
**Pull request by rhys-vdw**
Closes rhys-vdw/unity-destringer#10

### CODE REVIEW

**Comment by rhys-vdw** [comment]
So glad to discover OpenUPM yesterday. Very cool.

I had some issues opening the PR through the suggested flow btw. When it got to proposing the file (after the form) the "Propose new file" was disabled (even though I'd already forked). I ended up having to modify the URL so it was proposing it against my forked repo, then come back and open a PR manually. Seems to me that this is a GitHub error, but thought I'd flag it anyway.

**Comment by favoyang** [comment]
@rhys-vdw It's a known issue of GitHub, but I didn't find a reliable way to reproduce. But other folks report that you can change the filename field, then change it back to make the button enabled, or simply moving the cursor in the input field may fix it as well.

**Comment by rhys-vdw** [comment]
Thanks @favoyang. When does the package appear on openupm.com?

**Comment by favoyang** [comment]
Hmm... the file was added to the root path by mistake, that's why it didn't appear on the website. It should work a few minutes after https://github.com/openupm/openupm/commit/37b4775b5e8fdf8ae16afbbac7b1a554da4fb507 get merged.

**Comment by favoyang** [comment]
https://openupm.com/packages/games.feed.destringer/

**Comment by rhys-vdw** [comment]
@favoyang perhaps something to do with me modifying the URL?

**Comment by favoyang** [comment]
Could be.

**Pull request merged**
