### PR TITLE
Update com.rfadeev.unityforge.animcallbacks.yml

### PR DESCRIPTION
**Pull request by rfadeev**
Change package branch from master to upm.

### CODE REVIEW

**Comment by rfadeev** [comment]
@favoyang Hello, I wonder what else is needed from my side for the change to be propagated as if I do
```
openupm add com.rfadeev.unityforge.animcallbacks
```
I get master branch state of the package rather than upm branch one.

**Comment by favoyang** [comment]
Thanks for reporting the issue, I'll investigate later.

**Comment by favoyang** [comment]
Hi @rfadeev 

First I'll explain how it works. When you adding a new package via the website, it asks for a branch to detect the package.json. So it can verify and get some package information. When the yaml file was added to our build pipelines, only git tags are monitored. The _repoBranch_ field is no longer used, will be retired soon. So this PR is useless.

In your case, the 1.0.0 is built from commit [cef897c5eea1a5d498034e34afb7c053e45ff88c](https://github.com/rfadeev/unity-forge-anim-callbacks/commit/cef897c5eea1a5d498034e34afb7c053e45ff88c), which is equal to the git tag [1.0.0](https://github.com/rfadeev/unity-forge-anim-callbacks/tree/1.0.0) that is based on the master branch. Because you have some CI scripts modified the upm branch, you shall create git tag based on the upm branch instead.

To fix it
- bump the version number in the master branch
- commit and push, let the CI update the upm branch
- create a new git tag based on the upm branch
- wait openupm build pipelines to publish a new version

**Comment by rfadeev** [comment]
Hi @favoyang,

Many thanks for the detailed explanation. Indeed I thought that branch in the submission form matters hence this PR as I mentioned wrong branch (should be upm rather than master). Good to know openupm tracks tags to publish package versions. I've followed steps you proposed, new tag [1.0.1](https://github.com/rfadeev/unity-forge-anim-callbacks/tree/1.0.1) is set in upm branch (`package.json` was updated to have version 1.0.1 as well beforehand). Just checked and package version 1.0.1 published in openupm: https://openupm.com/packages/com.rfadeev.unityforge.animcallbacks/

**Comment by favoyang** [comment]
Glad to know it works!

**Pull request merged**
