### PR TITLE
Update com.jeffcampbellmakesgames.genesis.yml

### PR DESCRIPTION
**Pull request by jeffcampbellmakesgames**
Added code generation category

### CODE REVIEW

**Comment by jeffcampbellmakesgames** [comment]
@favoyang Do you have any idea why this might not result in a successful automatic merge? I just release a new update for this package using the right tag prefix and it hasn't seem to have deployed yet to OpenUPM and updating the package YAML on here seems to have resulted in a no-op as well. Thanks!

**Comment by favoyang** [comment]
Will investigate soon.

**Comment by favoyang** [comment]
@jeffcampbellmakesgames 

The delayed build has been fixed. I'm not sure why it happens though, will add more logs to trace the reason later.

An update YAML PR will not get merged automatically, it's a limitation of the mergebot. Ideally, if you're the hunter or owner of the package, your PR could get merged automatically. But such information is not provided by the Github events. So it's impossible for a generic mergebot to handle this. So the feature has been delayed due to limited resources.

**Comment by jzapdot** [comment]
Ah I see. Thanks for the clarification

**Comment by favoyang** [comment]
Debug info added in https://github.com/openupm/openupm/commit/25c6b883f4c8ba8c7112319eb42acacd4740f6f0. Will wait until it reproduces next time.

**Pull request merged**
