### PR TITLE
chore(data): new package com.oculus.unity.integration.vr

### PR DESCRIPTION
**Pull request by Morbeavus**

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @Morbeavus,

OpenUPM requires package to have an open-source license.

https://openupm.com/docs/adding-upm-package.html

> The package should use an open-source license. It's recommended to choose one from the [spdx license list (opens new window)](https://spdx.org/licenses/).

From the "Meta Platform Technologies SDK License Agreement"

> 1.2 General Restrictions. The License grant in this Section is solely for the purpose of developing, testing, and promoting your engines, tools, applications, content, games and demos, or other products and features (collectively, “Application”) and providing you and/or your end users access to MPT services and features through your Application as contemplated by applicable documentation accompanying the SDK. You may not (or allow those acting on your behalf to):
> ...
> 1.2.1 modify or create derivative works from any SDK or its component (other than sample source code described in this Section or expressly authorized by the documents accompanying the SDK);
> ...
> 1.2.8 use or redistribute the SDK or any portion thereof in any manner that would cause the SDK (or any portion thereof) or MPT to become subject to the terms of any open source license or other restrictions.

Though it has a section of redistribution 
> 1.3 Distribution and Sublicense Restrictions. The redistribution and sublicense rights under this Section are further subject to the following restrictions: (1) redistribution of sample source code or other materials must include the following copyright notice: “Copyright © Meta Platform Technologies, LLC and its affiliates. All rights reserved;” and (2) if the sample source code or other materials include a "License" or "Notice" text file, you must provide a copy of the License or Notice file with the sample code.

I'm not a lawyer. But it seems quite risk to "modify" the codebase and redistribute as an open-source package. I suggest you change your project license from MIT to Meta Platform Technologies SDK License Agreement, but I'm not 100% sure it is okay to redistribute it.

I have to reject this unless you get a direct feedback from Meta that this is encouraged.

**Review by favoyang — CHANGES_REQUESTED** [review]
Rejected for a license issue.

**Comment by Morbeavus** [comment]
Hello thanks for the response. I will look into the licenses.

I thought its okay since you allowed these packages: 
https://openupm.com/packages/com.oculus.sample-framework/
https://openupm.com/packages/com.oculus.unity-integration/

I changed the license in the repos but how to change it in the submit form since it wont be MIT?

We do not alter the SDK we just separated it into more packages so you can only take the parts that you really use.  Not all to reduce import and build times among the main reasons.

**Comment by favoyang** [comment]
> I changed the license in the repos but how to change it in the submit form since it wont be MIT?

Please modify two yml files in this PR:

```
licenseSpdxId: null
licenseName: Oculus SDK License
```
----
> I thought its okay since you allowed these packages:

That's a good point. I didn't think I manually reviewed these packages. It gets approved automatically by CI for the second-time contributor - @StephenHodgson. Thus, I want to invite StephenHodgson to this thread.

Since the Oculus SDK License(Meta Platform Technologies SDK License Agreement), allows redistribution for the sample code. The discussion will be limited to the three packages below
- com.oculus.unity-integration https://github.com/RageAgainstThePixel/com.oculus.unity-integration
- [com.oculus.unity.integration.vr](https://github.com/openupm/openupm/pull/3503/commits/173cda4af226370bf87995912f0e9bf45aaf7b77)
- [com.oculus.unity.integration.spatializer](https://github.com/openupm/openupm/pull/3503/commits/98807e22ee3f2bcf537533101fa7b9acede1c543)

The bottom line for OpenUPM is that a package must have an "open-source license", here I mean it should be
- source available - it's legal to get the source, read it, and execute it.
- allows for redistribution - so our pipelines can take the code and pack it into a UPM format (an NPM tarball).
- free to commercial or personal use.

A green open-source (free to modify and perhaps give up any other rights) is encourged, but not necessary.

From the Oculus SDK License:

> 1.2 General Restrictions. 
> You may not (or allow those acting on your behalf to):
> 1.2.1 modify or create derivative works from any SDK or its component (other than sample source code described in this Section or expressly authorized by the documents accompanying the SDK);
> ...
> 1.2.8 use or redistribute the SDK or any portion thereof in any manner that would cause the SDK (or any portion thereof) or MPT to become subject to the terms of any open source license or other restrictions.

Based on my understanding, it doesn't prevent you from redistributing the SDK, as long as you don't change the license, thus it won't "become subject to the terms of any open source license or other restrictions".

But I'm not sure whether split the SDK into a small portion will be considered as "modify or create derivative works from any SDK or its component"?

**Comment by StephenHodgson** [comment]
Yeah, I was also under the impression that the license could not be modified and should not be changed. I followed the recommendations from my lawyer to make sure there was no conflicts there.

There are minimal modifications to get the asset into upm package form, but it's versioned exactly the same as what is in the asset store. I'm not keen that the new packages are versioned differently. 

> But I'm not sure whether split the SDK into a small portion will be considered as "modify or create derivative works from any SDK or its component"?

I actually had to do this because of the size of the pull package being over 100mb which caused problems when uploading to hosting service.

Here are the two packages (although I have been falling behind keeping them up to date)
- https://github.com/RageAgainstThePixel/com.oculus.unity-integration 
- https://github.com/RageAgainstThePixel/com.oculus.sample-framework

**Review by StephenHodgson — CHANGES_REQUESTED** [review]
Here are my biggest concerns
- Licenses are incorrect
- package versioning is different from asset source
- parts of these packages have already been added to OpenUPM

**Comment by favoyang** [comment]
@StephenHodgson, thanks for the comment.

@Morbeavus, it's green light as long as you changed the license in the yaml files as well (https://github.com/openupm/openupm/pull/3503#issuecomment-1296298802)

Of course, it's another story if it gets Meta's attention someday for a different explanation of their license.

**Comment by StephenHodgson** [comment]
I definitely don't like that the versions of the packages are different that the source. Please fix that as well so people know what version of the asset it's from.

**Comment by favoyang** [comment]
> * Licenses are incorrect
> * package versioning is different from asset source
> * parts of these packages have already been added to OpenUPM

Agreed with the first two. The last one @Morbeavus probably did that on purpose?

**Comment by Morbeavus** [comment]
Well my end-goal:
1.  is having separate package for all the oculus tools (platform, vr, lipsync,audio-manager,etc) to allow modularity and control this only requires minimal change of adding the package.json and creating a repository for it (which we need to maintain anyway for our projects) so why not have it available to OpenUPM so others dont have to reinvent the wheel
2. Have all the version from 32 to current 46? 

The current version in the repos is something before version 32.0.0 (I have no idea what the version really is) and thats the lowest I can get my hands on. So after it gets green lit we can start versioning from 32.0.0 up and everything should be clear

**Comment by StephenHodgson** [comment]
Yeah I'm not stressed about the last bullet point. Just want to make sure we're not confusing people with additional packages and what is included in them.

**Comment by Morbeavus** [comment]
@StephenHodgson I have already prepared a collection package for all the "submodules" maybe we could collaborate on it in the future so we don't maintain two "similar" packages
https://github.com/Trisgram/com.oculus.unity.integration

**Comment by StephenHodgson** [comment]
> is having separate package for all the oculus tools (platform, vr, lipsync,audio-manager,etc) to allow modularity and control this only requires minimal change of adding the package.json and creating a repository for it (which we need to maintain anyway for our projects) so why not have it available to OpenUPM so others dont have to reinvent the wheel

This is a great idea. I think maybe we should just be explicit in the package readme about this maybe.

Also, might be easier to maintain in a monorepo.

**Comment by StephenHodgson** [comment]
TBH I just wish meta would publish this as UPM by default. One day 🥲

**Comment by Morbeavus** [comment]
> > is having separate package for all the oculus tools (platform, vr, lipsync,audio-manager,etc) to allow modularity and control this only requires minimal change of adding the package.json and creating a repository for it (which we need to maintain anyway for our projects) so why not have it available to OpenUPM so others dont have to reinvent the wheel
> 
> This is a great idea. I think we should just be explicit in the package readme about this maybe.
> 
> Also, might be easier to maintain in a monorepo.

Agree with the readme I want to work on the readme in next versions since I did not know if it will be possible to even push to OpenUPM

I have no experience with the monorepo so I can't say if the more tags in one repo or more repos with only relevant tags is better

**Comment by Morbeavus** [comment]
> @StephenHodgson, thanks for the comment.
> 
> @Morbeavus, it's green light as long as you changed the license in the yaml files as well ([#3503 (comment)](https://github.com/openupm/openupm/pull/3503#issuecomment-1296298802))
> 
> Of course, it's another story if it gets Meta's attention someday for a different explanation of their license.

I will do that asap

**Comment by StephenHodgson** [comment]
@Morbeavus are you also planning to update the versioning in the packages as well to better reflect the asset source?

**Comment by Morbeavus** [comment]
> @Morbeavus are you also planning to update the versioning in the packages as well to better reflect the asset source?

Definitely as I wrote earlier the current version of the package 1.0.0 is something we have in two years old project and we don't have documented what version it is but as we upgrade to 32.0.0 we will definetely know the version and then we can maintain it as it is on the here https://developer.oculus.com/downloads/package/unity-integration/32.0. Do you know if theres some file that maybe holds the vrsion information?

**Comment by StephenHodgson** [comment]
The [project.json file](https://github.com/RageAgainstThePixel/com.oculus.unity-integration/blob/development/Oculus%20Unity-Integration/Packages/com.oculus.unity-integration/package.json#L6)

**Comment by Morbeavus** [comment]
> The [project.json file](https://github.com/RageAgainstThePixel/com.oculus.unity-integration/blob/development/Oculus%20Unity-Integration/Packages/com.oculus.unity-integration/package.json#L6)

I meant in the Oculus integration asset if theres some file. Because I looked for chnagelog or something and few source files but could not find any mention of version thus the 1.0.0

**Comment by StephenHodgson** [comment]
Oh, not that I'm aware of. I just go by their download page and .unitypackage name

**Comment by StephenHodgson** [comment]
The Unity Asset store asset is also versioned, which is what they publish from the download archive

**Review by favoyang — APPROVED** [review]
Looks good

**Comment by favoyang** [comment]
Please let me know when it's ready to merge. It seems need some adjustments to align the versions (and git tags) with the asset store versions.

**Comment by Morbeavus** [comment]
> The Unity Asset store asset is also versioned, which is what they publish from the [download archive](https://developer.oculus.com/downloads/package/unity-integration-archive/)

Ah yes that one also only goes all the way down to 32 :/... our version has ovr plugin 1.61.0 while the 32 has 1.64.0

Well I will have to keep the first version 1.0.0 and next one will be 32.0.0 as we upgrade and test all the versions one by one in our project I guess we have our work cut out for us for the next week :D

**Comment by Morbeavus** [comment]
> Please let me know when it's ready to merge. It seems need some adjustments to align the versions (and git tags) with the asset store versions.

@StephenHodgson @favoyang so do you think we should upgrade to the 32 first before merging since we can't determine the accurate current version?

**Comment by StephenHodgson** [comment]
> so do you think we should upgrade to the 32 first before merging since we can't determine the accurate current version?

It would make me feel a lot better, but ultimately it's up to you on what you want to do with your package.

**Comment by StephenHodgson** [comment]
@Morbeavus also I accidentally gave you the wrong link 

https://developer.oculus.com/downloads/package/unity-integration

**Comment by favoyang** [comment]
You can of course request to merge with 1.0.0 first if you think this is a bit temporary for testing and give you more confident to upgrade to the better version that aligned with the "official" version. Just notice that it's possible but not encouraged to unpublish a published version in case you want to reset version for some reason later.

**Comment by Morbeavus** [comment]
> @Morbeavus also I accidentally gave you the wrong link
> 
> https://developer.oculus.com/downloads/package/unity-integration
> 
> The latest should be v46

The current version (1.0.0) is tested and works in a project so so I am fairly confident that we could "ship it".

I will probably upgrade to 32 make that initial version then 38, then 41 and then maintain all the versions from 46 and up since those are versions we need for our projects atm. - this will have to wait till tomorrow since I don't have access to any headsets to test it.

On the other hand if someone who uses the version in between then they will be out of luck so I am kinda looking for your advice here since you already have experience maintaining your package.

**Comment by StephenHodgson** [comment]
If you want to support older packages that's up to you. I just started at the version I was already working at. (I think it was v29)

It's really up to you if you want to make sure each version is useful for you and your team I guess. A lot of people might find this very useful if you have all the versions.

**Comment by Morbeavus** [comment]
@favoyang I have upgraded and tested the packages on the v32 you can merge. Now the first tag should be 32.0.0 for spatilizer and 31.2.0 for the VR.

**Pull request merged**
