### PR TITLE
Create com.google.firebase.app.yml

### PR DESCRIPTION
**Pull request by dinhtai1104**

### CODE REVIEW

**Comment by favoyang** [comment]
@dinhtai1104 

Thanks for submitting the package.

However, for a reason, Google has stopped using UPM as a format to publish their Unity software.

https://github.com/firebase/quickstart-unity/issues/1030

The one you submitted is trying to wrap the official software and make it a UPM package. It could be good work, but I can not publish it under the `com.google` scope. Only software directly maintained by Google can use that scope.

You can just contact the author to change the package name, or you'll have to use it directly from GitHub.

**Comment by favoyang** [comment]
BTW, there is an on-going discussion about this naming topic on our chat room https://discord.gg/FnUgWEP

**Comment by StephenHodgson** [comment]
Agreed. And exactly why my repository isn't already in the registry. I explicitly didn't add it for this reason @dinhtai1104

**Comment by dinhtai1104** [comment]
Sorry about that, I just want to test by add it to registry

**Pull request closed without merging**
