### PR TITLE
chore(data): new package jillejr.newtonsoft.json-for-unity.converters

### PR DESCRIPTION
**Pull request by jilleJr**
I might have been too slow for my other repo but this one is a first at least

:)

### CODE REVIEW

**Comment by favoyang** [comment]
@jilleJr thanks for submitting the package. It seems an unknown error here. I will have a look.

**Comment by favoyang** [comment]
@jilleJr The issue has been fixed now. It seems an unknown racing issue, but I'm not 100% sure about it. Anyway, I will pay more attention to a similar issue, if it happens.

**Comment by jilleJr** [comment]
Ah thank you! Quick reaction as well.

Say, why is it `com.github.*`?

**Comment by jilleJr** [comment]
Ah I see, it's the correct one at https://openupm.com/packages/jillejr.newtonsoft.json-for-unity.converters/

**Comment by favoyang** [comment]
Oh, my mistake. The correct package is https://openupm.com/packages/jillejr.newtonsoft.json-for-unity.converters/

The one you mentioned earlier is a fork for your JSON package.

**Pull request merged**
