### PR TITLE
chore(data): new package com.unity.2d.tilemap.extras

### PR DESCRIPTION
**Pull request by marcus-robinson**

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @marcus-robinson,

Thanks for your contribution. Packages that already existed on the Unity official registry are rejected. 

com.unity.2d.tilemap.extras => https://packages.unity.com/com.unity.2d.tilemap.extras

**Comment by erlioniel** [comment]
Hi @marcus-robinson ,
Looks like 2d-extras is listed in the Unity official registry, but it's not installable using Package Manager. I know, that up to Unity Technology to handle that (looks like they are filtered out it somehow or smth). But maybe you can just mirror it to be installable using OpenUPM CLI?

**Comment by favoyang** [comment]
Hi @erlioniel,

We decided not to mirror any packages that already existed on the official registry. You have two options:

**Opt 1: you can install any packages from the official registry via OpenUPM-CLI**

```sh
$ openupm view com.unity.2d.tilemap.extras

com.unity.2d.tilemap.extras@2.0.0-pre.1 | proprietary or unlicensed | versions: 4
...
versions:
  2.0.0-pre.1
  1.6.2-preview
  1.6.1-preview
  1.5.0-preview
```

Pick a version to install. AFAIK version `2.0.0-pre.1` requires `Unity 2021.1`, other versions work with `Unity 2020`.

```sh
$ openupm install com.unity.2d.tilemap.extras@1.6.2-preview
notice manifest added com.unity.2d.tilemap.extras@1.6.2-preview
notice please open Unity project to apply changes
```

Check the manifest changes

```
--- a/Packages/manifest.json
+++ b/Packages/manifest.json
@@ -50,7 +50,8 @@
     "com.unity.modules.video": "1.0.0",
     "com.unity.modules.vr": "1.0.0",
     "com.unity.modules.wind": "1.0.0",
-    "com.unity.modules.xr": "1.0.0"
+    "com.unity.modules.xr": "1.0.0",
+    "com.unity.2d.tilemap.extras": "1.6.2-preview"
   },
```

**Opt 2, you can also install any hidden package via the PackMan UI.** 

Just use the "Add package from git URL` menu, and then type the name of the package.

**Comment by erlioniel** [comment]
@favoyang thank you for the answer, managed before your answer with the second option. However, I think it might be slightly messy for people to find some packages using OpenUPL CLI and not able to find others.

Anyway, thank you very much for the reply and a great solution to keep everything up to date!

**Pull request closed without merging**
