### PR TITLE
Remove packages of cosmos53076

### PR DESCRIPTION
**Pull request by iGameMaker**

### CODE REVIEW

**Comment by favoyang** [comment]
Hi @iGameMaker,

Your packages (`com.github.cosmos53076.*`) has been purged from the registry. May I know the reason to remove them?

If you do want to remove those packages, I respect your choice. However please notice that as long as your project has an open source license, it does grant other developer the right to submit your packages to our platform for publishing. JFYI if it happens...

**Comment by iGameMaker** [comment]
Hi, Favo Yang
Actually I just wanna change my username of GitHub. The name like ‘cosmos53076’ is not a good name for remember or looking. I will reorganize all of my open-source projects, and add them into OpenUPM later. Don’t worry about this. I will be back. By the way, found a great open-source project created by Chinese on Github is a great thing. OpenUPM is a wonderful land. Keep going! (PS: If have a CDN server in China will be better. Since download package each time is a painful-waiting process.)


| |
Jerry Lee
|
|
cosmos53076@163.com
|


On 04/10/2020 18:28，Favo Yang<notifications@github.com> wrote：

Hi @iGameMaker,

Your packages (com.github.cosmos53076.*) has been purged from the registry. May I know the reason to remove them?

If you do want to remove those packages, I respect your choice. However please notice that as long as your project has an open source license, it does grant other developer the right to submit your packages to our platform for publishing. JFYI if it happens...

**Comment by favoyang** [comment]
@iGameMaker thanks for clarifying the reason. I will consider the suggestion to setup a mirror server in China.

**Comment by iDreamsOfGame** [comment]
Favo Yang,
I also have another question. Whether OpenUPM support other git hosting services, like gitlab.com or gitee.com?


| |
Jerry Lee
|
|
cosmos53076@163.com
|
签名由网易邮箱大师定制


On 04/10/2020 18:52，Favo Yang<notifications@github.com> wrote：

@iGameMaker thanks for clarifying the reason. I will consider the suggestion to setup a mirror server in China.

**Comment by favoyang** [comment]
Reasonable request, but not at this moment (low priority).

**Pull request merged**
