### PR TITLE
Update com.tendo.fuxi.yml

### PR DESCRIPTION
**Pull request by mistletoeKANO**

### CODE REVIEW

**Comment by mistletoeKANO** [comment]
fuxi-v1.0.4

**Comment by mistletoeKANO** [comment]
fuxi-v1.0.5

**Comment by mistletoeKANO** [comment]
fuxi-v1.0.6

**Comment by mistletoeKANO** [comment]
fuxi-v1.0.7

**Comment by mistletoeKANO** [comment]
fuxi-v1.0.7

**Comment by favoyang** [comment]
@mistletoeKANO why do you keep posting on this thread?

**Comment by mistletoeKANO** [comment]
>fuxi-v1.0.8

**Review by mistletoeKANO — COMMENTED** [review]
release 1.0.8

**Pull request merged**
