### PR TITLE
Update and rename dev.secretlab.yarnspinner.yml to dev.yarnspinner.unity.yml

### PR DESCRIPTION
**Pull request by desplesda**
(Whoops - forgot that I intended the package name to be based on the domain name for yarnspinner.dev.)

### CODE REVIEW

**Comment by favoyang** [comment]
I will clean the published old package (with package name dev.secretlab.yarnspinner) later today.

**Comment by favoyang** [comment]
@desplesda OpenUPM is tracking the Git tags. Hence you have to retag https://github.com/YarnSpinnerTool/YarnSpinner-Unity/releases 1.2.0 for the package name changes.

Otherwise, you can bump to 1.2.1 to fix the package name.

**Comment by desplesda** [comment]
Done! I untagged v1.2.0 and retagged it to https://github.com/YarnSpinnerTool/YarnSpinner-Unity/commit/0f366e571784b312e0114f2e7b50c77d89e74ff4. It looks like https://openupm.com/packages/dev.yarnspinner.unity/ is reporting a build error, "Version conflict".

**Comment by favoyang** [comment]
I have checked https://github.com/YarnSpinnerTool/YarnSpinner-Unity/commit/ae4c6d5cbe55448298fef12dce48115774561ab2 is the tag with both correct package 
name and version (bumped to) 1.2.2. I also set [1.2.2 to be the minimal version](https://github.com/openupm/openupm/commit/e749ed660a5f465389164efb8e67b22ae828017a#diff-1f13752c7780964390abf1d091ebc590) OpenUPM tracks to avoid confusing. Your next release should be greater or equal to v1.2.3.

The v1.2.2 has been processed successfully. Old package with name dev.secretlab.yarnspinner has been unpublished.

To automate the process of package release, please checkout
- Using GitHub Actions: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c
- Using CLI which gives you more control: https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163

**Comment by desplesda** [comment]
It looks like the most recent tags that have been published aren't being noticed by OpenUPM. Do I need to do anything else besides tag a release as a semver higher than v1.2.2? (Currently, we've published a v1.2.4 and a v1.2.5, but I'm not seeing them appear on OpenUPM.)

**Comment by favoyang** [comment]
Werd... working on it.

**Comment by favoyang** [comment]
@desplesda sorry for the inconvenience. It was a build-pipelines bug caused by handling `minVersion` the wrong way, which set to 1.2.2 for this repo.

https://openupm.com/packages/dev.yarnspinner.unity/
- v1.2.2, v1.2.4, and v1.2.5 are all good.
- v1.2.3 is version conflicted because of the [package.json](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/blob/3ff1e84c91ce2e7ee7633da5a38b9de37f23f35f/package.json) is still 1.2.2. Since it already bumps to 1.2.5, you can leave it here, or deleting tag 1.2.3. Our build pipelines will also remove the entry in 10 minutes. If you make such mistakes in the future, you can retag to fix it. Basically, if a package is not published, you can retag to fix, otherwise, you need to bump version to fix.

A refactor of build status will be landed later this year to give a better answer of "why my build is not there".

As always, if you find anything confusing, feel free to use this thread, or open a new issue to notify me.

**Comment by desplesda** [comment]
Thank you!

**Pull request merged**
